export const GET_CLIENTS_REQUEST = 'GET_CLIENTS_REQUEST';
export const GET_CLIENTS_AFTER_REORDER_REQUEST = 'GET_CLIENTS_AFTER_REORDER_REQUEST';
export const GET_CLIENTS_SUCCESS = 'GET_CLIENTS_SUCCESS';
export const GET_CLIENTS_FAIL = 'GET_CLIENTS_FAIL';

export const SEARCH_CLIENTS_REQUEST = 'SEARCH_CLIENTS_REQUEST';
export const SEARCH_CLIENTS_SUCCESS = 'SEARCH_CLIENTS_SUCCESS';
export const SEARCH_CLIENTS_FAIL = 'SEARCH_CLIENTS_FAIL';

export const GET_CLIENT_DETAILS_REQUEST = 'GET_CLIENT_DETAILS_REQUEST';
export const GET_CLIENT_DETAILS_SUCCESS = 'GET_CLIENT_DETAILS_SUCCESS';
export const GET_CLIENT_DETAILS_FAIL = 'GET_CLIENT_DETAILS_FAIL';

export const CREATE_CLIENT_REQUEST = 'CREATE_CLIENT_REQUEST';
export const CREATE_CLIENT_SUCCESS = 'CREATE_CLIENT_SUCCESS';
export const CREATE_CLIENT_FAIL = 'CREATE_CLIENT_FAIL';

export const REMOVE_CLIENT_REQUEST = 'REMOVE_CLIENT_REQUEST';
export const REMOVE_CLIENT_SUCCESS = 'REMOVE_CLIENT_SUCCESS';
export const REMOVE_CLIENT_FAIL = 'REMOVE_CLIENT_FAIL';

export const UPDATE_CLIENT_REQUEST = 'UPDATE_CLIENT_REQUEST';
export const UPDATE_CLIENT_SUCCESS = 'UPDATE_CLIENT_SUCCESS';
export const UPDATE_CLIENT_FAIL = 'UPDATE_CLIENT_FAIL';

export const UPDATE_CLIENT_PICTURE_REQUEST = 'UPDATE_CLIENT_PICTURE_REQUEST';
export const UPDATE_CLIENT_PICTURE_SUCCESS = 'UPDATE_CLIENT_PICTURE_SUCCESS';
export const UPDATE_CLIENT_PICTURE_FAIL = 'UPDATE_CLIENT_PICTURE_FAIL';

export const GET_ORGANIZATIONS_REQUEST = 'GET_ORGANIZATIONS_REQUEST';
export const GET_ORGANIZATIONS_SUCCESS = 'GET_ORGANIZATIONS_SUCCESS';
export const GET_ORGANIZATIONS_FAIL = 'GET_ORGANIZATIONS_FAIL';

export const OPEN_DETAILS_WINDOW = 'OPEN_DETAILS_WINDOW';
export const CLOSE_DETAILS_WINDOW = 'CLOSE_DETAILS_WINDOW';
